### ISSUE TITLE
You have to select the quit option twice for the app to quit

### ISSUE THREAD

**Issue by tbodt** [vindo-app/vindo#2]
You have to select the quit option twice for the app to quit.

**Comment by tbodt** [comment]
I'm not quite sure why this is happening. Will investigate. At some point.

**Comment by tbodt** [comment]
New info: Occasionally, it quits when you click quit once. Occasionally. Probably something about threads.

**Comment by jaka2015** [comment]
It doesn't really matter though.

**Comment by tbodt** [comment]
Now it works.
