### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jaka2015** [vindo-app/vindo#3]
Can you change the version from 0.1 Beta to 0.3?

**Comment by tbodt** [comment]
Why 0.3?

**Comment by tbodt** [comment]
Actually, it would be 0.3 alpha.

**Comment by jaka2015** [comment]
no just call it 0.3 cuz 1.0 will be the final. 0.5 and up will be beta. the reason for 0.3 is that the beamng tech demo was called 0.3 and i figured that we could skip a version since we’ve made so many improvements.

**Comment by tbodt** [comment]
I still want to say whether it's alpha or beta or what. Let's talk about it in #6.

**Comment by tbodt** [comment]
Closing to get it out of the way for 1.0.
